name: Deploy to firebase

on:
  release:
    types:
      - published

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: npm ci
    - name: Build App
      run: npm run build 
      env:
        CI: false
    - name: Test App
      run: npm run test --if-present
    - name: Check Directory
      run: ls .
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
        build-application: false
